### ISSUE TITLE
Visitor counter missing

### ISSUE THREAD

**Issue by alyyousuf7** [SaraVieira/make-frontend-shit-again#10]
There used to be a visitor counter at the bottom of almost every website.

**Comment by c4talyst** [comment]
This is a duplicate of https://github.com/SaraVieira/make-frontend-shit-again/issues/7

**Comment by SaraVieira** [comment]
You are right sir ! Added in the bottom of page ! 

https://makefrontendshitagain.party/ 💃

**Comment by alyyousuf7** [comment]
The counter says `no link no work`
![counter](https://user-images.githubusercontent.com/14050128/40003982-255752b4-57ae-11e8-82c1-8aeaf029e6d2.png)

**Comment by SaraVieira** [comment]
I have added the link and see when it comes back.

Ill leave the issue open for now

**Comment by SaraVieira** [comment]
Fixed 💃
