### ISSUE TITLE
Missing w3c compliance badges

### ISSUE THREAD

**Issue by c4talyst** [SaraVieira/make-frontend-shit-again#12]
You could include the w3c compliant badges, if it were w3c compliant. https://validator.w3.org/nu/?doc=https%3A%2F%2Fmakefrontendshitagain.party%2F

**Comment by SaraVieira** [comment]
True !

I can't make it because of the marquee tag but added the badges at the bottom: https://github.com/SaraVieira/make-frontend-shit-again/commit/0c907d01f21ac47532a2aef171218cf5873c06a9 😄
