### ISSUE TITLE
Cannot see link previews

### ISSUE THREAD

**Issue by aaronransley** [SaraVieira/make-frontend-shit-again#2]
First of all, I love this project! I stumbled across it on HN and immediately felt inspired.

I saw you were using microlink.io, but am noticing that none of the link previews are loading. I'm on FF / Win 10 and my console is [filled with CORS errors](https://www.dropbox.com/s/8xaotk6c6fpj6cs/cap.png?dl=1)

I'm not sure this is a problem with your impl though, since the microlinks docs are [having the same issue](https://docs.microlink.io/sdk/)

`o/`

**Comment by sudovijay** [comment]
Thats 429 ! TooManyRequestsException So it probably reached the limit i.e 250 reqs/ Per day

**Comment by sudovijay** [comment]
She has like 50 website links in there thats 50 requests per user , so she gonna hit the limit in no time, and the pricing seems to be high too https://microlink.io/#pricing , all they doing is fetching open graph data mostly, not worth it. instead its easier to make a script [ be it shell / any ] to fetch og images then either use remote urls or store them locally & use them,

**Comment by SaraVieira** [comment]
Hey !

Yes , that was uncessary and I removed microlink and just used https://github.com/withspectrum/micro-open-graph to get all the stuff 💃
