### ISSUE TITLE
autoplay audio player

### ISSUE THREAD

**Issue by filosofikode** [SaraVieira/make-frontend-shit-again#3]
where is the autoplay audio player that fixed-placed on top?

**Comment by SaraVieira** [comment]
Have any songs in mind ? 🤔

**Comment by Aluriak** [comment]
The ones at [www.cameronsworld.net](https://www.cameronsworld.net/music/) fits well, could be a good start.

**Comment by christianparpart** [comment]
songs? `nyan cat` may be a little to time-travel but is as punishing as the sounds being played back in time.

**Comment by danlbob** [comment]
[Movie_Themes_-_Titanic_-_My_Heart_Will_Go_On_(Techno_Mix).mid.zip](https://github.com/SaraVieira/make-frontend-shit-again/files/2002394/Movie_Themes_-_Titanic_-_My_Heart_Will_Go_On_.Techno_Mix.mid.zip)

**Comment by SaraVieira** [comment]
Holy cow! I will put the titanic one 🔊

**Comment by SaraVieira** [comment]
https://makefrontendshitagain.party/

It now plays the song :DDDD

**Comment by danlbob** [comment]
I'm not a huge fan of being able to play/pause it... definitely `display: none;` on those controls
