### ISSUE TITLE
please add a "homepage" view counter

### ISSUE THREAD

**Issue by christianparpart** [SaraVieira/make-frontend-shit-again#7]
I really like your retro idea, but to be honest, I still remember (like a decease) that literally every page around y2k had a very visibly present page view counter.

It'd be awesome to have that on your homepage, too.

other random thoughts:
* jQuery is to modern to be listed, too.
* where's the "Made with HTML 4.01 strict" logo?
* where are the (back in time) state-of-the-art `frameset`'s with some frame violating the cruel design of the rest?

**Comment by SaraVieira** [comment]
You are right sir ! Added in the bottom of page ! 

https://makefrontendshitagain.party/ 💃

**Comment by SaraVieira** [comment]
I am also adding all the HTML and best viewed logos now 😄 

About the frameset... It doesn't work anymore and my standards don't allow me ahah

**Comment by SaraVieira** [comment]
Added all the badges too 💃
