### ISSUE TITLE
Rename the "inspiration websites" section to "friends websites"

### ISSUE THREAD

**Issue by fsferrara** [SaraVieira/make-frontend-shit-again#71]
Sure you remember that page or section of an old site containing links to "friends websites". In some cases, there were a list of banners instead of links.
God how I hated the fact that those links were completely unrelated to the website content :-D but it is still fun!

With this issue, I am proposing to rename the "inspiration websites" section to "friends websites" in order to recreate that section. No changes at the URLs list are in scope.

I hope you like this idea.

**Comment by SaraVieira** [comment]
Hey!

This sounds like an awesome idea!  Wanna make a small PR for that? You can just change it in the english translation JSON file here: https://github.com/SaraVieira/make-frontend-shit-again/blob/master/locales/en.json#L10

**Comment by SaraVieira** [comment]
Closed as completed by #72
