### ISSUE TITLE
No MIDI file is automatically played

### ISSUE THREAD

**Issue by claudiodangelis** [SaraVieira/make-frontend-shit-again#9]
**Expected result**

Websites are supposed to play a welcoming, software-syntesized song as the users land on them. See: http://www.4camosci.it/

**Actual result**

No MIDI file was played _(nor **downloaded**, boo modern browsers!)_

**Comment by SaraVieira** [comment]
https://makefrontendshitagain.party/

It now plays a song :DDDD

in mp3 tho
